#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
     path: /{_locale}
     controller: App\Controller\HomeController::home
     requirements:
          _locale: en|fr|ar
          default: fr

aboutus:
     path: /{_locale}/about-us
     controller: App\Controller\HomeController::aboutUs
     requirements:
          _locale: en|fr|ar
          default: fr

contact:
     path: /{_locale}/contact
     controller: App\Controller\HomeController::contact
     requirements:
          _locale: en|fr|ar
          default: fr


user.profile:
     path: /{_locale}/{slug}
     controller: App\Controller\UserController::profile
     requirements:
          _locale: en|fr|ar
          default: fr

user.register:
     path: /{_locale}/register
     controller: App\Controller\UserController::register
     requirements:
          _locale: en|fr|ar
          default: fr

user.login:
     path: /{_locale}/login
     controller: App\Controller\UserController::login
     requirements:
          _locale: en|fr|ar
          default: fr

user.edit:
     path: /{_locale}/{slug}/edit
     controller: App\Controller\UserController::edit
     requirements:
          _locale: en|fr|ar
          default: fr

admin.events.show:
     path: /{_locale}/admin/events
     controller: App\Controller\Admin\AdminEventsController::show
     requirements:
          _locale: en|fr|ar

admin.event.edit:
     path: /{_locale}/admin/event/{id}
     controller: App\Controller\Admin\AdminEventsController::edit
     methods:  GET|POST
     requirements:
          _locale: en|fr|ar
          id: '\d+'


admin.event.remove:
     path: /{_locale}/admin/event/{id}
     controller: App\Controller\Admin\AdminEventsController::remove
     methods: DELETE
     requirements:
          _locale: en|fr|ar
          id : '\d+'


admin.event.create:
     path: /{_locale}/admin/event/create
     controller: App\Controller\Admin\AdminEventsController::create
     requirements:
          _locale: en|fr|ar


admin.users.create:
     path: /{_locale}/admin/users/create
     controller: App\Controller\Admin\AdminUsersController::create
     requirements:
          _locale: en|fr|ar


